---
channel: edge
addons:
  sharry:
    repository: mdegat01/addon-sharry
    target: sharry
    image: ghcr.io/mdegat01/sharry/{arch}
  sharry2:
    repository: erdnaxela02/sharry2
    target: sharry
    image: ghcr.io/erdnaxela02/sharry2/{arch}
