---
channel: edge
addons:
  sharry:
    repository: erdnaxela02/addon-sharry
    target: sharry
    image: ghcr.io/erdnaxela02/sharry/{arch}
  sharry-dependency-less:
    repository: erdnaxela02/addon-sharry-dependency-less
    target: sharry
    image: ghcr.io/erdnaxela02/sharry-dependency-less/{arch}
  p2pool:
    repository: erdnaxela02/addon-p2pool
    target: p2pool
    image: ghcr.io/erdnaxela02/p2pool/{arch}
