---
channel: edge
addons:
  sharry:
    repository: erdnaxela02/addon-sharry
    target: sharry
    image: ghcr.io/erdnaxela02/sharry/{arch}
  sharryperso:
    repository: erdnaxela02/sharry2
    target: sharry
    image: ghcr.io/erdnaxela02/sharry/{arch}
