---
channel: edge
addons:
  sharry:
    repository: casse-boubou/addon-sharry
    target: sharry
    image: ghcr.io/casse-boubou/sharry/{arch}
  sharry-dependency-less:
    repository: casse-boubou/addon-sharry-dependency-less
    target: sharry
    image: ghcr.io/casse-boubou/sharry-dependency-less/{arch}
  p2pool:
    repository: casse-boubou/addon-p2pool
    target: p2pool
    image: ghcr.io/casse-boubou/p2pool/{arch}
  monerod:
    repository: casse-boubou/addon-monerod
    target: monerod
    image: ghcr.io/casse-boubou/monerod/{arch}
