---
channel: edge
addons:
  sharry:
    repository: erdnaxela02/addon-sharry
    target: sharry
    image: ghcr.io/erdnaxela02/sharry/{arch}
  sharry-1:
    repository: erdnaxela02/addon-sharry-1
    target: sharry
    image: ghcr.io/erdnaxela02/sharry-1/{arch}
