arch:
- aarch64
auth_api: true
backup_post: s6-svc -wd -d /run/s6/legacy-services/mariadb-lock/
backup_pre: s6-svc -wU -u /run/s6/legacy-services/mariadb-lock/
codenotary: erdnaxela02@hotmail.fr
description: Sharry pour Home Assistant sans dependances a Mariadb
image: ghcr.io/erdnaxela02/sharry-dependency-less/{arch}
init: false
map:
- share:rw
name: Sharry-dependency-less
options:
  conf_overrides: []
  databases:
  - sharry
  default_language: us
  domain: homeassistant.local
  log_level: info
  logins:
  - password: null
    username: homeassistant
  rights:
  - database: sharry
    username: homeassistant
  server_secret: null
  share_max_size_gb: 1.5
  share_max_valid_days: 365
  theme: light
  use_ssl: false
ports:
  3306/tcp: null
  9090/tcp: 9090
ports_description:
  3306/tcp: Mariadb port
  9090/tcp: HTTP listen port
schema:
  conf_overrides:
  - property: match(^sharry[.]restserver[.][-.a-z0-9]+)
    value: str
  copy_db: bool?
  copy_db_source: list(database|filesystem)?
  copy_db_target: list(database|filesystem)?
  databases:
  - str
  defaultStore: list(database|filesystem)
  default_language: match([A-Za-z]{2})?
  domain: match([^\/:]+)
  local_db: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  logins:
  - password: password
    username: str
  remote_db_database: str?
  remote_db_host: str?
  remote_db_password: password?
  remote_db_port: port?
  remote_db_type: list(mariadb|postgres)?
  remote_db_username: str?
  reset_database: bool?
  rights:
  - database: str
    privileges:
    - list(ALTER|CREATE|CREATE ROUTINE|CREATE TEMPORARY TABLES|CREATE VIEW|DELETE|DELETE
      HISTORY|DROP|EVENT|GRANT OPTION|INDEX|INSERT|LOCK TABLES|SELECT|SHOW VIEW|TRIGGER|UPDATE)?
    username: str
  server_secret: password
  share_max_size_gb: float(0.01,)?
  share_max_valid_days: int(1,)?
  theme: list(light|dark)?
  use_ssl: bool?
services:
- mysql:provide
slug: sharry-dependency-less
url: https://github.com/erdnaxela02/addon-sharry-dependency-less
version: 1.2.0
watchdog: http://[HOST]:9090/api/v2/open/info/version
webui: http://[HOST]:[PORT:9090]
